const a = 4;
const b = 2;

document.getElementById("container").innerHTML = a + b;

document.getElementById("calculateSumButton").addEventListener("click", () => {
    document.getElementById("sum").innerHTML = 
        Number(document.getElementById("a").value) + 
        Number(document.getElementById("b").value);
})

document.getElementById("redButton").addEventListener("click", () => {
  document.body.style.backgroundColor = "red";  
})

document.getElementById("greenButton").addEventListener("click", () => {
    document.body.style.backgroundColor = "green";  
})

document.getElementById("blueButton").addEventListener("click", () => {
    document.body.style.backgroundColor = "blue";  
})

const button = document.createElement("button");
button.innerHTML = "This is a Button generated by JS";
document.body.appendChild(button);